# application.yml
server:
  port: 8686
spring:
  application:
    name: book-audit
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true  # Enable service discovery
        service-name: book-audit  # Optional: Custom service name
        register: true
        instanceId: ${spring.application.name}:${spring.cloud.client.hostname}
  #        :${server.port}
  data:
    mongodb:
      uri: mongodb://localhost:27017/books_audit
      username: mongodb
      password: mongodb
      profiles:
        active: dev
#kafka
kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#management
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    org.springframework.data.mongodb.core: debug
    org.springframework.cloud.consul: DEBUG






